# Dynamic Programming

In [30]:
import numpy as np

In [42]:
# items hash table include each items weight and the value
items = {}
items['item1'] = [10, 1000]
items['item2'] = [5, 1500]
items['item3'] = [20, 2000]
items['item4'] = [10, 1500]
items['item5'] = [25, 2500]

In [43]:
# maximum weight knapsack can hold
knapsack = 25

In [54]:
def DynamicPro(items, knapsack):
    grid = np.zeros((5,5))
    for j, item in enumerate(items):
        w, v = items[item]
        for k in range(1, len(grid)+1, 1):
            if k*5 >= w:
                if j > 0 and k < knapsack:
                    grid[k-1][j] = max(grid[k-1][j-1], v + (grid[k-1 -(w//5)][j-1] if (k-1)>=(w//5) else 0))
                else:
                    grid[k-1][j] = v
            else:
                if j > 0:
                    grid[k-1][j] = grid[k-1][j-1]
                else:
                    continue
    print(grid)

In [55]:
DynamicPro(items, knapsack)

[[    0.  1500.  1500.  1500.  1500.]
 [ 1000.  1500.  1500.  1500.  1500.]
 [ 1000.  2500.  2500.  3000.  3000.]
 [ 1000.  2500.  2500.  3000.  3000.]
 [ 1000.  2500.  3500.  4000.  4000.]]
